# 1Panel专用Docker Compose配置
# 使用预构建镜像，确保部署成功

services:
  mpdstreaming:
    # 使用Docker Hub预构建镜像
    image: xinmeng96/mpdstreaming:latest
    container_name: mpd-hls-streamer
    ports:
      - "8080:8080"
    volumes:
      # 配置文件将由容器自动创建
      - mpd-config:/app/config
      - ./logs:/app/logs
      - /tmp/hls:/tmp/hls
    environment:
      - CONFIG_PATH=/app/config/config.yaml
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=INFO
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python3", "/app/healthcheck.py", "--quiet"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - mpd-network

  # Nginx反向代理和HLS文件服务
  nginx:
    image: nginx:alpine
    container_name: mpd-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - /tmp/hls:/usr/share/nginx/html/hls:ro
    depends_on:
      - mpdstreaming
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  mpd-network:
    driver: bridge

volumes:
  mpd-config:
    driver: local
